# Deploy a STAC Browser website to github pages
name: STAC Browser

on: workflow_dispatch

# These are picked up by 'npm run build'
env:
  SB_catalogUrl: "https://raw.githubusercontent.com/${{ github.repository }}/main/catalog.json"
  SB_pathPrefix: "/${{ github.event.repository.name }}/"
  SB_historyMode: "hash"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout STAC Browser Source
      uses: actions/checkout@v4
      with:
        repository: radiantearth/stac-browser
        ref: v3.1.0

    # Overwrite config with file from this repository
    - name: Configure STAC Browser
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          config.js
        sparse-checkout-cone-mode: false

    - name: Install STAC Browser
      run: |
        npm install .

    - name: Build Website
      run: |
        npm run build --

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload just 'dist/' folder
        path: 'dist'
        
  # https://github.com/actions/deploy-pages
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 
