# Deploy a STAC Browser website to github pages
name: STAC Browser

on: workflow_dispatch

env:
  SB_catalogUrl: "https://raw.githubusercontent.com/${{ github.repository }}/main/catalog.json"
  # TILE_SOURCE_TEMPLATE: "https://api.cogeo.xyz/cog/tiles/{z}/{x}/{y}?url={ASSET_HREF}&expression=sqrt(b1)&rescale=0,1"
  SB_pathPrefix: "/${{ github.event.repository.name }}/"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout STAC Browser Source
      uses: actions/checkout@v4
      with:
        repository: radiantearth/stac-browser
        ref: v3.1.0

    - name: Install STAC Browser
      run: |
        npm install .

    - name: Build Website
      run: |
        npm run build -- --SB_catalogUrl="${{ env.CATALOG_URL }}" \
        --SB_pathPrefix="${{ env.PATH_PREFIX }}" \
        --SB_historyMode=hash

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
