
name: STAC Updater

permissions:
   contents: write
   pull-requests: write
   
on:
  # Run once per day at midnight
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
  AWS_NO_SIGN_REQUEST: YES
  AWS_REGION: us-west-2

jobs:
  build-and-test:
    if: github.repository != 'relativeorbit/aws-rtc-stac'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
       cache-environment: true
       environment-file: environment.yml

    - name: Generate STAC
      run: |
        ./s1_rtc_stac.py

    - name: Validate STAC
      run: |
        stac version
        # stac validate --recursive --no-links --no-assets catalog.json

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "update catalog through ${{ steps.date.outputs.date }}"
        title: "Update STAC (${{ steps.date.outputs.date }})"
        reviewers: "scottyhq"
        body: |
          Update catalog through ${{ steps.date.outputs.date }})
