name: STAC Validator

on: [workflow_dispatch, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install stactools
      run: |
        pip install stactools[s3,validate]

    - name: Validate STAC
      shell: bash
      run: |
        stac validate --recursive --no-links --no-assets catalog.json
